config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  devise_for :users
  root to: 'posts#index'
  # get 'posts', to: 'posts#index'
  # resources :posts, only: [:index, :new, :create]
  # resources :users, only: [:index, :new, :edit]

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "ログインしました"
      posts_path
    end
  
  def after_sign_out_path_for(resource)
    flash[:alert] = "ログアウトしました"
      root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) 
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :contact)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    render "posts/index"
  end

  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  \# ログアウト
  def destroy
    super
    session[:keep_signed_out] = true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
   end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.haml
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :contact
    = f.text_area :contact
  .actions
    = f.submit 'Save'

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
%h1 Listing contacts

%table
  %thead
    %tr
      %th Name
      %th Contact
      %th
      %th
      %th

  %tbody
    - @contacts.each do |contact|
      %tr
        %td= contact.name
        %td= contact.contact
        %td= link_to 'Show', contact
        %td= link_to 'Edit', edit_contact_path(contact)
        %td= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.haml
%h1 New contact

= render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @contact.name
%p
  %b Contact:
  = @contact.contact

= link_to 'Edit', edit_contact_path(@contact)
\|
= link_to 'Back', contacts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Webcloak2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/index.html.haml
.wrapper
  = render "shared/user-nav"
  = render "shared/my-cloak"
  = render "shared/pickup"
  = render "shared/footer-contents"

app/views/posts/new.html.haml
.user-nav
  .header
    .header__logo
      =image_tag 'mainlogo', size: "180x40", alt: "login" 
  .nav
    .nav__outer
      = link_to "#" do
        =image_tag 'j.png', size: "40x40", alt: "outer"
    .nav__tops
      = link_to "#" do
        =image_tag 'T.png', size: "40x40", alt: "tops"
    .nav__bottoms
      = link_to "#" do
        =image_tag 'istockphoto-1009622864-1024x1024.png', size: "40x40", alt: "bottoms"
    .nav__edit
      = link_to new_post_path do
        <i class="fas fa-camera-retro"></i>
    .nav__config
      = link_to "#" do
        <i class="fas fa-cogs"></i>
    .nav__logout
      = link_to root_path do
        <i class="fas fa-sign-out-alt"></i>
.title
  NEW Item Input
 
.form
 

app/views/posts/top.html.haml
.main-container
  %h1= image_tag 'mainlogo', size: "400x90", alt: "background"
  - if user_signed_in?
    %h2
      HELLO! #{current_user.name}
    %h4
      メールアドレス： #{current_user.email}
    = link_to "ログアウト", destroy_user_session_path, method: :delete
  - else
    %h2 You are not logged in
    .button-box
      .button-box__btn1
        = link_to user_session_path do
          =image_tag 'button1.png', size: "150x65", alt: "login"
      .button-box__btn2
        = link_to new_user_registration_path do
          =image_tag 'button2.png', size: "150x65", alt: "signin"

app/views/shared/_footer-contents.html.haml
.footer-continer
  .footer
    .footer__title
      %p Recommend Items!
  .contents
    .slide
      =image_tag '1.jpg', size: "150x150", alt: "1"
    .slide
      =image_tag '2.jpg', size: "150x150", alt: "2"
    .slide
      =image_tag '3.jpg', size: "150x150", alt: "3"
    .slide
      =image_tag '4.jpg', size: "150x150", alt: "4"
    .slide
      =image_tag '5.jpg', size: "150x150", alt: "5"
    .slide
      =image_tag '6.jpg', size: "150x150", alt: "6"
    .slide
      =image_tag '7.jpg', size: "150x150", alt: "7"
    .slide
      =image_tag '8.jpg', size: "150x150", alt: "8"
    .slide
      =image_tag '9.jpg', size: "150x150", alt: "9"

  

app/views/shared/_my-cloak.html.haml
.my-cloak
  .header
    .header__title
      %h2 My Cloak
    .header__weather
      = image_tag "名称未設定-6.png", size: "60x50", alt: "weather"
    .header__comment
      %p 曇時々雨 60% 14°/9° 大阪 /12/17(TUE) 
  .contents
    .contents__box
      = image_tag "jacket.jpg", size: "200x200", alt: "jacket"
    .contents__box
      = image_tag "jacket2.jpg", size: "200x200", alt: "jacket2"
    .contents__box
      = image_tag "jacket3.jpg", size: "200x200", alt: "jacket3"
    .contents__box
      = image_tag "jacket4.jpg", size: "200x200", alt: "jacket4"
    .contents__box
      = image_tag "jacket5.jpg", size: "200x200", alt: "jacket5"
    .contents__box
      = image_tag "jacket6.jpg", size: "200x200", alt: "jacket6"
    .contents__box
      = image_tag "jacket7.jpg", size: "200x200", alt: "jacket7"
    .contents__box
      = image_tag "jacket8.jpg", size: "200x200", alt: "jacket8"
    .contents__box
      = image_tag "jacket9.jpg", size: "200x200", alt: "jacket9" 
    .contents__box
      = image_tag "jacket10.jpg", size: "200x200", alt: "jacket10"
    .contents__box
      = image_tag "jacket11.jpg", size: "200x200", alt: "jacket11"
    .contents__box
      = image_tag "jacket12.jpg", size: "200x200", alt: "jacket12"
    .contents__box
      = image_tag "jacket13.jpg", size: "200x200", alt: "jacket13" 
    .contents__box
      = image_tag "jacket14.jpg", size: "200x200", alt: "jacket14" 
    .contents__box
      = image_tag "jacket15.jpg", size: "200x200", alt: "jacket15" 
    .contents__box
      = image_tag "jacket16.jpg", size: "200x200", alt: "jacket16" 
    .contents__box
      = image_tag "jacket17.jpg", size: "200x200", alt: "jacket17" 
    .contents__box
      = image_tag "jacket18.jpg", size: "200x200", alt: "jacket18" 
    .contents__box
      = image_tag "jacket19.jpg", size: "200x200", alt: "jacket19" 
    .contents__box
      = image_tag "jacket20.jpg", size: "200x200", alt: "jacket20"
  

app/views/shared/_pickup.html.haml
.pickup
  .comment
    %a PickUp Style!
  .contents
    .contents__imeage
      = link_to "https://wear.jp/haruki0607/15874382/" do
        = image_tag "wear.jpg", size: "260x330", alt: "pickup"
  .stutas 
    = image_tag "frame2.png", size: "260x250", alt: "pickup"
    .stutas__comment
      %p このチェックブルゾンめちゃくちゃお気に入り☺️✨チェック柄がとっても可愛くて素材もしっかりしているので大活躍間違いなしです😊👌

app/views/shared/_user-nav.html.haml
.user-nav
  .header
    .header__logo
      =image_tag 'mainlogo', size: "180x40", alt: "login" 
  .nav
    .nav__outer
      = link_to "#" do
        =image_tag 'j.png', size: "40x40", alt: "outer"
    .nav__tops
      = link_to "#" do
        =image_tag 'T.png', size: "40x40", alt: "tops"
    .nav__bottoms
      = link_to "#" do
        =image_tag 'istockphoto-1009622864-1024x1024.png', size: "40x40", alt: "bottoms"
    .nav__edit
      = link_to "#" do
        <i class="fas fa-camera-retro"></i>
    .nav__config
      = link_to "#" do
        <i class="fas fa-cogs"></i>
    .nav__logout
      = link_to root_path do
        <i class="fas fa-sign-out-alt"></i>
  
    